services:
  danielm_demobundle.twig_extension:
    class: Danielm\DemoBundle\Twig\DemoTwigExtension
    public: false
    tags:
      - { name: twig.extension }

  danielm_demobundle.service:
    class: Danielm\DemoBundle\Service\DemoService
    public: false
    arguments:
      $container: '@container'

  Danielm\DemoBundle\Contract\DemoServiceInterface: '@danielm_demobundle.service'

  Danielm\DemoBundle\Controller\:
      resource: '../src/Controller/*'
      autowire: true
      autoconfigure: true

  Danielm\DemoBundle\Command\:
    resource: '../src/Command/*'
    autowire: true
    autoconfigure: true
